[package]
org= "ballerinax"
name= "azure.ad"
version= "1.0.1-SNAPSHOT"
authors = ["Ballerina"]
keywords = ["azure", "active directory", "directory service"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.ad"
license = ["Apache-2.0"]

[build-options]
observability-included=true
