[package]
distribution = "2201.0.0"
org= "ballerinax"
name= "azure.ad"
version= "2.2.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Security & Identity Tools", "Cost/Freemium", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.ad"
license = ["Apache-2.0"]

[build-options]
observability-included=true
